project:
  type: book
  output-dir: docs/es

book:
  title: "Datos a escala humana"
  subtitle: "Datos abiertos para ciudades resilientes"
  author: "Nissim Lebovits"
  site-url: https://nlebovits.github.io/datos-escala-humana/es/
  repo-url: https://github.com/nlebovits/datos-escala-humana
  language: es
  chapters:
    - es/intro.qmd
    - part: Python Geoespacial
      chapters:
        - es/python-geoespacial/index.qmd
        - es/python-geoespacial/taller.ipynb
    - part: Datos Abiertos
      chapters:
        - es/datos-abiertos/index.qmd
        - es/datos-abiertos/taller.ipynb
    - part: Riesgo Clim√°tico para Ciudades
      chapters:
        - es/riesgo-climatico/index.qmd
        - es/riesgo-climatico/taller.ipynb
    - part: Datos a la Acci√≥n
      chapters:
        - es/datos-accion/index.qmd
        - es/datos-accion/taller.ipynb
    - part: Cookbooks
      chapters:
        - es/cookbooks/pergamino-final.ipynb
        - es/cookbooks/esperanza.ipynb
        # - es/cookbooks/la-plata.ipynb
        - es/cookbooks/villa-del-rosario.ipynb
    - es/references.qmd
  sidebar:
    pinned: true
    align: center
    style: "docked"
    logo: /public/book-logo.png
    search: true
    collapse-level: 1
    footer: |
      [üá™üá∏ ES](https://nlebovits.github.io/datos-escala-humana/es/) | [üá∫üá∏ EN](https://nlebovits.github.io/datos-escala-humana/en/)
  page-footer:
    right: "This page is built with ‚ù§Ô∏è and [Quarto](https://quarto.org/)."
    center: '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1">'
    left: '&copy; [Nissim Lebovits](https://nlebovits.github.io), 2025'

format:
  html:
    code-summary: "Mostrar c√≥digo"
