project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  chapters:
    - index.qmd

bibliography: references.bib

execute:
  ipynb: false  # Don't execute .ipynb files, use outputs already embedded
  # .qmd files will still execute normally

format:
  html:
    toc: true
    toc_float: true
    grid:
      sidebar-width: 400px
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-link: true
    code-fold: false
    code-copy: true
    code-overflow: wrap
    css: styles.css
    number-sections: true
    fontsize: "11"
    lightbox: auto


filters:
  - include-files.lua
  - quarto
