project:
  type: book
  output-dir: docs/en

book:
  title: "Human Scale Data"
  subtitle: "Open data for resilient cities"
  author: "Nissim Lebovits"
  site-url: https://nlebovits.github.io/datos-escala-humana/en/
  repo-url: https://github.com/nlebovits/datos-escala-humana
  language: en
  chapters:
    - en/intro.qmd
    - part: Geospatial Python
      chapters:
        - en/python-geospatial/python-geospatial.qmd
    - part: Open Data
      chapters:
        - en/open-data/open-data.qmd
    - part: Climate Risk for Cities
      chapters:
        - en/climate-risk/climate-risk.qmd
    - part: Data to Action
      chapters:
        - en/data-action/data-action.qmd
    - part: Cookbooks
      chapters:
        - en/cookbooks/pergamino.qmd
        - en/cookbooks/esperanza.ipynb
        - en/cookbooks/la-plata.qmd
        - en/cookbooks/villa-del-rosario.ipynb
    - en/references.qmd
  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    logo: /public/book-logo.png
    footer: |
      [üá™üá∏ ES](https://nlebovits.github.io/datos-escala-humana/es/) | [üá∫üá∏ EN](https://nlebovits.github.io/datos-escala-humana/en/)
  page-footer:
    right: "This page is built with ‚ù§Ô∏è and [Quarto](https://quarto.org/)."
    center: '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1">'
    left: '&copy; [Nissim Lebovits](https://nlebovits.github.io), 2025'

format:
  html:
    code-summary: "Show code"
