project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  chapters:
    - index.qmd
    - en/intro.qmd
    - part: "Python GIS"
      chapters:
        - en/python-geospatial/python-geospatial.qmd
    - part: "Open Data"
      chapters:
        - en/open-data/open-data.qmd
    - part: "Climate Risk"
      chapters:
        - en/climate-risk/fundamentals.qmd
        - en/climate-risk/hazard.qmd
        - en/climate-risk/risk.qmd
    - part: "From Data to Action"
      chapters:
        - en/data-to-action/data-to-action.qmd
    - part: "Cookbooks"
      chapters:
        - en/cookbooks/la-plata.qmd
        - en/cookbooks/pergamino.qmd
    - en/references.qmd

bibliography: references.bib

execute:
  freeze: auto  # Only re-execute when source changes
  cache: true   # Cache computation results
  daemon: true  # Use Jupyter daemon for faster startup

format:
  html:
    toc: true
    toc_float: true
    grid:
      sidebar-width: 400px
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-link: true
    code-fold: false
    code-copy: true
    code-overflow: wrap
    css: styles.css
    number-sections: true
    fontsize: "11"
    lightbox: auto


filters:
  - include-files.lua
  - quarto